export const restArray = [
  {
    id: 0,
    title: "Пицца плюс",
    time: 50,
    rating: 4.5,
    price: 900,
    type: "Пицца",
    image: "rest-1.jpg",
  },
  {
    id: 1,
    title: "Тануки",
    time: 50,
    rating: 4.5,
    price: 900,
    type: "Пицца",
    image: "rest-2.jpg",
  },
  {
    id: 2,
    title: "FoodBand",
    time: 50,
    rating: 4.5,
    price: 900,
    type: "Пицца",
    image: "rest-3.jpg",
  },
  {
    id: 3,
    title: "Жадина-пицца",
    time: 50,
    rating: 4.5,
    price: 900,
    type: "Пицца",
    image: "rest-4.jpg",
  },
  {
    id: 4,
    title: "Точка еды",
    time: 50,
    rating: 4.5,
    price: 900,
    type: "Пицца",
    image: "rest-5.jpg",
  },
  {
    id: 5,
    title: "PizzaBurger",
    time: 50,
    rating: 4.5,
    price: 900,
    type: "Пицца",
    image: "rest-6.jpg",
  },
];

export const goodArray = [{
  id: 0,
  title: "Ролл угорь стандарт",
  description: 'Рис, угорь, соус унаги, кунжут, водоросли нори.',
  price: 900,
  image: "good-1.jpg",
},
{
  id: 1,
  title: "Калифорния лосось стандарт",
  description: 'Рис, лосось, авокадо, огурец, майонез, икра масаго, водоросли нори.',
  price: 900,
  image: "good-2.jpg",
},
{
  id: 2,
  title: "Окинава стандарт",
  description: 'Рис, креветка отварная, сыр сливочный, лосось, огурец свежий...',
  price: 900,
  image: "good-3.jpg",
},
{
  id: 3,
  title: "Цезарь маки хl",
  description: 'Рис, куриная грудка копченая, икра масаго, томат, айсберг, соус цезарь...',
  price: 900,
  image: "good-4.jpg",
},
{
  id: 4,
  title: "Ясай маки стандарт 185 г",
  description: 'Рис, помидор свежий, перец болгарский, авокадо, огурец, айсберг',
  price: 900,
  image: "good-5.jpg",
},
{
  id: 5,
  title: "Ролл с креветкой стандарт",
  description: 'Рис, водоросли нори, креветки отварные, сыр сливочный, огурцы',
  price: 900,
  image: "good-6.jpg",
},
];